language: python

before_install:
  # for rpm-py-installer
  - sudo apt-get install -y rpm

install:
 - pip install --upgrade pip setuptools
 - pip install tox

script:
  - tox

matrix:
  include:
  - python: "2.6"
    env: TOXENV=py26-django16
  - python: "2.7"
    env: TOXENV=py27-django16
  - python: "2.7"
    env: TOXENV=py27-django18
  - python: "3.4"
    env: TOXENV=py34-django18
  - python: "3.5"
    env: TOXENV=py35-django18
  - python: "3.6"
    env: TOXENV=py36-django18
  - python: "3.6"
    env: TOXENV=py36-cov-travis
